version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./your_project:/app/your_project
    environment:
      DEBUG: "True"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
    restart: always  
  
  redis:
    image: redis:latest
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: easymodeldb
      POSTGRES_USER: easymodel
      POSTGRES_PASSWORD: easymodel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always 
  
  nginx:
    image: nginx:latest
    container_name: my_nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # 挂载 Nginx 配置
      - /etc/letsencrypt:/etc/letsencrypt  # 挂载 SSL 证书目录
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
    driver: local

